#!/usr/bin/env python
# coding: utf-8
"""
Register unwarped BOLD EPI space to individual T2w template via the unwarped SBRef
- Final step of functional preprocessing following BOLD motion and distortion corrections
"""

import nipype.interfaces.utility as util
import nipype.interfaces.ants as ants
import nipype.pipeline.engine as pe


def build_wf_template():

    # Template inputs
    inputs = pe.Node(
        util.IdentityInterface(
            fields=[
                'bold_preproc',
                'sbref_preproc',
                'seepi_preproc'
                'tpl_t2_brain'
            ]
        ),
        name='inputs'
    )

    # Rigid body register T2w SE-EPI midspace generated by TOPUP to individual T2w template
    reg_seepi_tpl = pe.Node(
        ants.RegistrationSynQuick(
            transform_type='r',
            num_threads=4
        ),
        name='reg_seepi_tpl',
        terminal_output=None,
    )


    # Resample T2w SE-EPI midspace to individual template space
    resamp_seepi_tpl = pe.Node(
        ants.WarpImageMultiTransform(
            num_threads=4
        ),
        name='resamp_seepi_tpl'
    )

    # Resample BOLD SBRef to individual template space
    resamp_sbref_tpl = pe.Node(
        ants.WarpImageMultiTransform(
            use_nearest=True,
            num_threads=4
        ),
        name='resamp_sbref_tpl'
    )

    # Define workflow outputs
    outputs = pe.Node(
        util.IdentityInterface(
            fields=[
                'seepi_tpl',
                'sbref_tpl',
                'bold_tpl'
            ]
        ),
        name='outputs'
    )

    # Template registration workflow setup
    wf_template = pe.Workflow(name='wf_template')

    wf_template.connect([

        # Register SE-EPI unwarped midspace to individual template space
        (inputs, reg_seepi_tpl, [
            ('tpl_t2_brain', 'fixed_image'),
            ('seepi_preproc', 'moving_image')
        ]),

        # Resample SE-EPI midspace to template space
        (inputs, resamp_seepi_tpl, [
            ('tpl_t2_brain', 'fixed_image'),
            ('t1_ind', 'moving_image')
        ]),

        # Resample unwarped BOLD SBRef to template space
        (inputs, resamp_sbref_tpl, [
            ('tpl_t2_brain', 'fixed_image'),
            ('t1_ind', 'moving_image')
        ]),

        # Resample SE-EPI midspace to template space
        (inputs, resamp_seepi_tpl, [
            ('tpl_t2_brain', 'fixed_image'),
            ('t1_ind', 'moving_image')
        ]),

        # Warp atlas T1 into indEPI space
        (inputs, resamp_t1_atlas2epi, [('t1_atlas', 'input_image')]),
        (inputs, resamp_t1_atlas2epi, [('epi_ind', 'reference_image')]),
        (merge_tx_files, resamp_t1_atlas2epi, [('out', 'transformation_series')]),

        # Warp atlas labels into indEPI space
        (inputs, resamp_labels_atlas2epi, [('labels_atlas', 'input_image')]),
        (inputs, resamp_labels_atlas2epi, [('epi_ind', 'reference_image')]),
        (merge_tx_files, resamp_labels_atlas2epi, [('out', 'transformation_series')]),

        # Output results
        (resamp_seepi_tpl, outputs, [('warped_image', 'seepi_tpl')]),
        (resamp_sbref_tpl, outputs, [('output_image', 'sbref_tpl')]),
    ])

    return wf_template

# --- RETIRED CODE ---
# Fast SyN register preprocessed SBRef to individual T2w template space
# Leave this code here until linear registration validated
# reg_sbref_to_indT2 = pe.Node(
#     ants.RegistrationSynQuick(
#         transform_type='s',
#         num_threads=4
#     ),
#     name='reg_sbref_to_indT2',
#     terminal_output=None,
#     needed_outputs=[
#         'forward_warp_field',
#         'inverse_warp_field',
#         'out_matrix',
#         'warped_image'
#     ]
# )

# Create multitransform list of ANTs warp and affine files
# [atlas-t1 warp, atlas-t1 affine, t1-epi affine]
# merge_tx_files = pe.Node(
#     util.Merge(3),
#     name='merge_tx_files'
# )
