"""
Create PDF report for slabpreproc pipeline, including QC

AUTHORS
----
Mike Tyszka, Ph.D., Caltech Brain Imaging Center

DATES
----
2013-09-25 JMT From scratch
2013-10-23 JMT Add com external call
2013-10-24 JMT Move stats calcs to new stats.py
2019-05-28 JMT Recode as a nipype interface class
2019-05-29 JMT Expand to multiple pages
2022-09-07 JMT Adapt for slabpreproc

MIT License

Copyright (c) 2022 Mike Tyszka

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import os
import bids
import os.path as op
import datetime as dt
import pandas as pd
import nibabel as nib

from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (SimpleDocTemplate,
                                Paragraph,
                                Spacer,
                                Image,
                                Table,
                                PageBreak)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from ..utils import graphics


class ReportPDF:

    def __init__(self, report_dir, report_files, metadata):
        """

        :param report_dir: str, directory
            Full path to report output folder for this subject/session
        :param report_files: dict
            Dictionary of paths to files used to generate report
        :param metadata: dict
            Source BOLD metadata from JSON sidecar
        """

        self._report_dir = report_dir
        self._deriv_dir = op.dirname(report_dir)
        self._report_files = report_files
        self._metadata = metadata

        # Create report dir for this subject/session if needed
        if not op.isdir(report_dir):
            os.makedirs(report_dir, exist_ok=True)

        # Get BIDS keys from BOLD filename
        keys = bids.layout.parse_file_entities(self._report_files['SourceBOLD'])
        subj_id, sess_id, task_id = keys['subject'], keys['session'], keys['task']

        # Load header info from BOLD Nifti file
        bold_nii = nib.load(self._report_files['SourceBOLD'])
        bold_hdr = bold_nii.header

        # Merge image file metadata into main dict
        self._metadata['Subject'] = subj_id
        self._metadata['Session'] = sess_id
        self._metadata['Task'] = task_id
        self._metadata['MatrixSize'] = bold_hdr.get_data_shape()
        self._metadata['VoxelSize'] = bold_hdr.get_zooms()[:3]

        # General prefix
        self._prefix = f'sub-{subj_id}_ses-{sess_id}_task-{task_id}'

        # Build report PDF filename
        self._report_pdf_fname = op.join(report_dir, f'{self._prefix}_report.pdf')

        # Contents - list of flowables to be built into a PDF document
        self._contents = []

        # Add a justified paragraph style
        self._pstyles = getSampleStyleSheet()
        self._pstyles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))

        self._init_pdf()
        self._add_summary()
        self._add_motion_timeseries()
        self._add_image_montages()
        self._doc.build(self._contents)

    def _init_pdf(self):

        # Create a new PDF document
        self._doc = SimpleDocTemplate(
            self._report_pdf_fname,
            pagesize=letter,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.5 * inch
        )

    def _add_summary(self):

        ptext = '<font size=24>Slab Preprocessing SummaryReport</font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.5 * inch))

        timestamp = dt.datetime.now().strftime('%Y-%m-%d at %H:%M:%S')
        ptext = f'<font size=12>Generated by slabpreproc on {timestamp}</font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.25 * inch))

        # Session information
        ptext = '<font size=14><b>Session Information</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.1 * inch))

        demo = [
            ['Subject', self._metadata['Subject']],
            ['Session', self._metadata['Session']],
            ['Scan Time', self._metadata['AcquisitionTime']],
            ['Software Version', self._metadata['SoftwareVersions']],
            ['Pulse Sequence', self._metadata['SequenceName']],
            ['Coil Name', self._metadata['ReceiveCoilName']],
            ['', '']
        ]

        image = [
            ["Repetition Time (ms)", f"{self._metadata['RepetitionTime'] * 1e3}"],
            ["Echo Time (ms)", f"{self._metadata['EchoTime'] * 1e3}"],
            ["Voxel Size (mm)", ' x '.join([f'{a:0.1f}' for a in self._metadata['VoxelSize']])],
            ["Matrix Size", ' x '.join([f'{a:d}' for a in self._metadata['MatrixSize']])],
            ["EPI Echo Spacing (us)", f"{self._metadata['EffectiveEchoSpacing'] * 1e6:0.0f}"],
            ["RO Bandwidth (Hz/pix)", f"{self._metadata['PixelBandwidth']}"],
            ["PE Bandwidth (Hz/pix)", f"{self._metadata['BandwidthPerPixelPhaseEncode']}"]
        ]

        demo_table = Table(demo, hAlign='LEFT')
        image_table = Table(image, hAlign='LEFT')

        self._contents.append(Table([[demo_table, image_table]]))
        self._contents.append(Spacer(1, 0.25 * inch))

    def _add_motion_timeseries(self):

        # Load motion parameter table
        motion_df = pd.read_csv(self._report_files['MotionTable'])

        # Scale rotations to milliradians
        motion_df['Rx_mrad'] = motion_df['Rx_rad'] * 1e3
        motion_df['Ry_mrad'] = motion_df['Ry_rad'] * 1e3
        motion_df['Rz_mrad'] = motion_df['Rz_rad'] * 1e3

        # Page break
        self._contents.append(PageBreak())

        # Motion Parameter Timeseries
        ptext = '<font size=14><b>Motion Parameter Timeseries</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        ptext = """
        <font size=11>
        Head motion correction displacements, rotations and framewise displacements (FD) over time
        </font>
        """
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        # Build motion timeseries plot
        figsize = (7, 5.0)
        motion_ts_png = self._gen_fig_fname('motion_ts')
        graphics.plot_motion_timeseries(motion_df, motion_ts_png, figsize)

        # Add figure to report
        mo_ts_img = Image(motion_ts_png, figsize[0] * inch, figsize[1] * inch, hAlign='LEFT')
        self._contents.append(mo_ts_img)

        self._contents.append(Spacer(1, 0.2 * inch))

        # FD and lpf FD power spectra
        ptext = '<font size=14><b>Motion Power Spectrum</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        ptext = """
        <font size=11>
        Power spectrum of the framewise displacement time course.
        </font>
        """
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        # Build motion power spectrum plot
        figsize = (7, 2.5)
        motion_ps_png = self._gen_fig_fname('motion_ps')
        graphics.plot_motion_powerspec(motion_df, motion_ps_png, figsize)

        motion_ps_img = Image(motion_ps_png, figsize[0] * inch, figsize[1] * inch, hAlign='LEFT')
        self._contents.append(motion_ps_img)

        self._contents.append(Spacer(1, 0.2 * inch))

    def _add_image_montages(self):

        # Get slab limits from mean SE-EPI and use for all montages
        zlims = graphics.crop_to_slab(self._report_files['mSEEPI'])

        self._section_title('Anatomic Templates', page_break=True)
        self._add_montage(img_name='T1wHead', title='T1w Head', colormap='gray', zlims=zlims)
        self._add_montage(img_name='T2wHead', title='T2w Head', colormap='gray', zlims=zlims)

        self._section_title('Atlas Labels', page_break=True)
        self._add_montage(img_name='Labels', under_name='T1wHead',
                          title='Atlas Labels', colormap='rainbow', zlims=zlims, scaling='default')

        self._section_title('Preprocessed EPI', page_break=True)
        self._add_montage(img_name='mSEEPI', title='Mean SE-EPI', colormap='gray', zlims=zlims)
        self._add_montage(img_name='tMean', title='Temporal mean BOLD', colormap='gray', zlims=zlims)

        self._section_title('Fieldmaps', page_break=True)
        self._add_montage(img_name='B0rads', title='TOPUP B0 Fieldmap (rad/s)', colormap='seismic', zlims=zlims)

        self._section_title('Quality Control', page_break=True)
        self._add_montage(img_name='tSFNR', title='Temporal SFNR', colormap='gnuplot2', zlims=zlims)
        self._add_montage(img_name='Dropout', title='Estimated BOLD dropout', colormap='magma', zlims=zlims)

    def _add_montage(
            self,
            img_name,
            title,
            under_name=None,
            colormap='gray',
            scaling='robust',
            mont_rows_cols=(3, 6),
            fig_width=7.0,
            zlims=(0, -1)
    ):
        """
        Add axial image montage to report PDF

        :param img_name: str
            Report files dictionary field name
        :param title: str
            Figure title
        :param under_name: str
            Optional underlay field name [None]
        :param colormap:
            Figure colormap (default 'gray')
        :param scaling: str
            Intensity scaling ('default' or 'robust')
        :param mont_rows_cols: tuple
            Montage size (rows, cols)
        :param fig_width:
            Figure width in inches (default 7.0 for Letter size)
        :return:
            None
        """

        # Load entire image and crop to slab
        src_img = nib.load(self._report_files[img_name]).get_fdata()
        slab_img = src_img[:, :, zlims[0]:zlims[1]]

        # Optional underlay image
        if under_name:
            under_img = nib.load(self._report_files[under_name]).get_fdata()
            under_img = under_img[:, :, zlims[0]:zlims[1]]
        else:
            under_img = []

        png_fname = self._gen_fig_fname(img_name)
        hw_ratio = graphics.image_montage(
            slab_img, under_img, png_fname, dims=mont_rows_cols,
            cmap_name=colormap, scaling=scaling
        )

        self._section_title(title, subsection=True)

        montage_img = Image(png_fname, fig_width * inch, fig_width * hw_ratio * inch, hAlign='LEFT')

        self._contents.append(montage_img)
        self._contents.append(Spacer(1, 0.2 * inch))

    def _gen_fig_fname(self, suffix):

        return op.join(self._report_dir, f'{self._prefix}_{suffix}.png')

    def _section_title(self, section_title, subsection=False, page_break=False):

        # Optional page break
        if page_break:
            self._contents.append(PageBreak())

        # Smaller font and post title gap for subsection titles
        if subsection:
            fontsize = 11
            postgap = 0.1
        else:
            fontsize = 14
            postgap = 0.4

        ptext = f'<font size={fontsize}><b>{section_title}</b></font>'

        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, postgap * inch))
