"""
Create PDF report for slabpreproc pipeline, including QC

AUTHORS
----
Mike Tyszka, Ph.D., Caltech Brain Imaging Center

DATES
----
2013-09-25 JMT From scratch
2013-10-23 JMT Add com external call
2013-10-24 JMT Move stats calcs to new stats.py
2019-05-28 JMT Recode as a nipype interface class
2019-05-29 JMT Expand to multiple pages
2022-09-07 JMT Adapt for slabpreproc

MIT License

Copyright (c) 2022 Mike Tyszka

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import os
import bids
import os.path as op
import datetime as dt
import pandas as pd
from glob import glob

from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (SimpleDocTemplate,
                                Paragraph,
                                Spacer,
                                Image,
                                Table,
                                PageBreak)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from ..utils import graphics


class ReportPDF:

    def __init__(self, report_dir, report_files, metadata):
        """

        :param report_dir: str, directory
            Full path to report output folder for this subject/session
        :param report_files: dict
            Dictionary of paths to files used to generate report
        :param metadata: dict
            Source BOLD metadata from JSON sidecar
        """

        self._report_dir = report_dir
        self._deriv_dir = op.dirname(report_dir)
        self._report_files = report_files
        self._metadata = metadata

        # Create report dir for this subject/session if needed
        if not op.isdir(report_dir):
            os.makedirs(report_dir, exist_ok=True)

        # Get BIDS keys from BOLD filename
        keys = bids.layout.parse_file_entities(self._report_files['SourceBOLD'])
        subj_id, sess_id, task_id = keys['subject'], keys['session'], keys['task']

        # Add subject, session and task IDs to metadata dict
        self._metadata['Subject'] = subj_id
        self._metadata['Session'] = sess_id
        self._metadata['Task'] = task_id

        # General prefix
        self._prefix = f'sub-{subj_id}_ses-{sess_id}_task-{task_id}'

        # Build report PDF filename
        self._report_pdf_fname = op.join(report_dir, f'{self._prefix}_report.pdf')

        # Contents - list of flowables to be built into a PDF document
        self._contents = []

        # Add a justified paragraph style
        self._pstyles = getSampleStyleSheet()
        self._pstyles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))

        self._init_pdf()
        self._add_summary()
        self._add_motion_timeseries()
        self._add_image_montages()
        self._doc.build(self._contents)

    def _init_pdf(self):

        # Create a new PDF document
        self._doc = SimpleDocTemplate(
            self._report_pdf_fname,
            pagesize=letter,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.5 * inch
        )

    def _add_summary(self):

        ptext = '<font size=24>Slab Preprocessing SummaryReport</font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.5 * inch))

        timestamp = dt.datetime.now().strftime('%Y-%m-%d at %H:%M:%S')
        ptext = f'<font size=12>Generated by slabpreproc on {timestamp}</font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.25 * inch))

        # Session information
        ptext = '<font size=14><b>Session Information</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.1 * inch))

        demo = [
            ['Subject', self._metadata['Subject']],
            ['Session', self._metadata['Session']],
            ['Scan Time', self._metadata['AcquisitionTime']],
            ['Software Version', self._metadata['SoftwareVersions']],
            ['Pulse Sequence', self._metadata['SequenceName']],
            ['Coil Name', self._metadata['ReceiveCoilName']],
            ['', '']
        ]

        image = [
            ['Repetition Time', '{} ms'.format(self._metadata['RepetitionTime'] * 1e3)],
            ['Echo Time', '{} ms'.format(self._metadata['EchoTime'] * 1e3)],
            # ['Voxel Size', '{} mm'.format(self._metadata['VoxelSize'])],
            # ['Matrix Size', self._metadata['MatrixSize']],
            ['EPI Echo Spacing', '{0:.0f} us'.format(self._metadata['EffectiveEchoSpacing'] * 1e6)],
            ['RO Bandwidth', '{} Hz/pix'.format(self._metadata['PixelBandwidth'])],
            ['PE Bandwidth', '{} Hz/pix'.format(self._metadata['BandwidthPerPixelPhaseEncode'])]
        ]

        demo_table = Table(demo, hAlign='LEFT')
        image_table = Table(image, hAlign='LEFT')

        self._contents.append(Table([[demo_table, image_table]]))
        self._contents.append(Spacer(1, 0.25 * inch))

    def _add_motion_timeseries(self):

        # Load motion dataframe
        motion_csv = self._find_file('qc', 'recon-motion_pars.csv')
        motion_df = pd.read_csv(motion_csv)

        # Build motion timeseries plot
        motion_ts_png = self._gen_fig_fname('motion_ts')
        graphics.plot_motion_timeseries(motion_df, motion_ts_png)

        # Build motion power spectrum plot
        motion_ps_png = self._gen_fig_fname('motion_ps')
        graphics.plot_motion_powerspec(motion_df, motion_ps_png)

        # Page break
        self._contents.append(PageBreak())

        #
        # Motion Parameter Timeseries
        #

        ptext = '<font size=14><b>Motion Parameter Timeseries</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        #
        ptext = """
        <font size=11>
        Head motion correction parameter timeseries
        </font>
        """
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        mo_ts_img = Image(motion_ts_png, 7.0 * inch, 3.5 * inch, hAlign='LEFT')
        self._contents.append(mo_ts_img)

        self._contents.append(Spacer(1, 0.2 * inch))

        # FD and lpf FD power spectra
        ptext = '<font size=14><b>Motion Power Spectra</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        ptext = """
        <font size=11>
        Power spectrum of the absolute displacement and total rotation timecourses.
        dB scale referenced to maximum spectral power.
        </font>
        """
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.2 * inch))

        motion_ps_img = Image(motion_ps_png, 7.0 * inch, 3.5 * inch, hAlign='LEFT')
        self._contents.append(motion_ps_img)

        self._contents.append(Spacer(1, 0.2 * inch))

    def _add_image_montages(self):

        # Page break
        self._contents.append(PageBreak())

        ptext = '<font size=14><b>Image Sections</b></font>'
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.25 * inch))

        self._add_montage('Temporal Mean', self._fnames['TMeanMontage'])
        self._add_montage('Temporal Standard Deviation', self._fnames['TSDMontage'])
        self._add_montage('Regions of Interest', self._fnames['ROIsMontage'])

    def _add_montage(self, title, img_fname):

        ptext = '<font size=11><b>{}</b></font>'.format(title)
        self._contents.append(Paragraph(ptext, self._pstyles['Justify']))
        self._contents.append(Spacer(1, 0.1 * inch))

        tmean_montage_img = Image(img_fname, 7.0 * inch, 2.4 * inch, hAlign='LEFT')

        self._contents.append(tmean_montage_img)
        self._contents.append(Spacer(1, 0.25 * inch))

    def _find_file(self, subdir, suffix):

        search_dir = op.join(self._deriv_dir, subdir)
        candidates = sorted(glob(op.join(search_dir, f'*{suffix}*')))
        return candidates[0]

    def _gen_fig_fname(self, suffix):
        return op.join(self._report_dir, f'{self._prefix}_{suffix}.png')